version: 2.1

orbs:
  docker: circleci/docker@2.0.3
  rust: circleci/rust@1.6.0

executors:
  rust-executor:
    working_directory: ~/animeboys-bot
    machine:
      image: ubuntu-2204:2023.07.1
    resource_class: arm.medium

jobs:
  publish-docker:
    executor: rust-executor
    steps:
      - rust/install
      - docker/publish:
          context:
            - DOCKERHUB
          image: "jmorales15/animeboys-bot"
          tag: $(cat ./Cargo.toml | grep version | head -1 | grep -o '"[^"]\+"' | sed -e 's/^"//' -e 's/"$//')
          filters:
            branches:
              only: /main/
workflows:
  deploy-production:
    jobs:
      - publish-docker
