version: 2.1

orbs:
  docker: circleci/docker@2.0.3

executors:
  rust-executor:
    working_directory: ~/animeboys-bot
    machine:
      image: ubuntu-2204:2023.07.1
    resource_class: arm.medium

jobs:
  publish-docker:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - docker/publish:
          context:
            - DOCKERHUB
          image: "jmorales15/animeboys-bot"
          tag: $(cat ./Cargo.toml | grep version | head -1 | grep -o '"[^"]\+"' | sed -e 's/^"//' -e 's/"$//')
          filters:
            branches:
              only: /main/
workflows:
  deploy-production:
    jobs:
      - docker/publish:
          context:
            - DOCKERHUB
          executor: rust-executor
          image: "jmorales15/animeboys-bot"
          tag: $(cat ./Cargo.toml | grep version | head -1 | grep -o '"[^"]\+"' | sed -e 's/^"//' -e 's/"$//')
          filters:
            branches:
              only: /main/

      - docker/publish:
          name: publish-docker-prod
          context:
            - DOCKERHUB
          image: "jmorales15/animeboys-bot"
          tag: latest
          filters:
            branches:
              only: /main/
